apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "fluentd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-client
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fluentd.name" . }}
      release: {{ .Release.Name }}
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "fluentd.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "sh"
          args:
            - "-c"
            -  "{{- if .Values.plugins }} {{- range .Values.plugins }} fluent-gem install {{ . }};{{- end }}{{- end }} /run.sh"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OUTPUT_BUFFER_CHUNK_LIMIT
              value: {{ .Values.output.buffer_chunk_limit | quote }}
            - name: OUTPUT_BUFFER_QUEUE_LIMIT
              value: {{ .Values.output.buffer_queue_limit | quote }}
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.output.host | quote }}
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.output.port | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.output.scheme | quote }}
            - name: FLUENT_ELASTICSEARCH_USER
              value: {{ .Values.fluentESUser | quote }}
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: {{ .Values.fluentESPassword | quote }}
            - name: S3_BUCKET 
              value: {{ .Values.s3Bucket }}
            - name: S3_BUCKET_PATH
              value: {{ .Values.s3BucketPath }}
            - name: S3_REGION 
              value: {{ .Values.s3Region }}
            - name: FLUENTD_PRIVATE_KEY_PASSPHRASE
              value: {{ .Values.fluentdPrivateKeyPassphrase | quote }}
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fluentd.fullnameshort" . }}-auth
                  key: awsSecKey
            - name: AWS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "fluentd.fullnameshort" . }}-auth
                  key: awsKeyId
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
  {{ toYaml .Values.resources | indent 12 }}
          ports:
  {{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
  {{- end }}
            - name: http-input
              containerPort: 9880
              protocol: TCP
          volumeMounts:
            - name: {{ template "fluentd.fullnameshort" . }}-vol
              mountPath: /etc/fluent/config.d
            - name: buffer
              mountPath: "/var/log/fluentd-buffers"
            {{- if .Values.enableTLS }}
            - name: certs
              mountPath: "/fluentd/etc/ssl"
            {{- end }}
      volumes: 
        {{- if .Values.enableTLS }}
        - name: certs
          secret: 
            secretName: fluentd-tls 
        {{- end }}
        - name: {{ template "fluentd.fullnameshort" . }}-vol
          configMap:
            name: {{ template "fluentd.fullname" . }}
        - name: buffer
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "fluentd.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
