apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "fluentd.fullname" . }}-auth
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: {{ template "fluentd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: logging-client
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "namewithversion" . }}
stringData:
    awsSecKey: "{{ .Values.awsSecKey }}"
    awsKeyId: "{{ .Values.awsKeyId }}"
